spring.application.name=usuario3

spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuario
spring.datasource.username=postgres
spring.datasource.password=moacir91443208
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080
